version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: backend-app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: frontend-app
    depends_on:
      - backend
